# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('travel_date_to', models.DateField(null=True)),
                ('travel_date_from', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='trips',
            name='joined_trips',
            field=models.ManyToManyField(related_name='joined_trips', to='Belt.Users'),
        ),
        migrations.AddField(
            model_name='trips',
            name='new_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_trip', to='Belt.Users'),
        ),
    ]
