# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Belt', '0002_auto_20170927_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='user',
            new_name='new_trip',
        ),
        migrations.AlterField(
            model_name='trips',
            name='travel_date_from',
            field=models.DateField(null=True),
        ),
    ]
