# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Belt', '0003_auto_20170927_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='description',
            field=models.CharField(default='description', max_length=255),
            preserve_default=False,
        ),
    ]
