# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Belt', '0004_trips_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='description',
        ),
    ]
